### ISSUE TITLE
alpha channel vertically offset

### ISSUE THREAD

**Issue by easrng** [jakearchibald/stacked-alpha-video#3]
seen on your blog post on Firefox for Android 129 on a Pixel 8a
![Screenshot_20240806-185043](https://github.com/user-attachments/assets/94c17ee6-6672-4cf6-9ad3-4b635e13310d)

**Comment by jakearchibald** [comment]
Firefox 128 is the latest version as far as I can see, and it works fine. Are you on a different release channel?

**Comment by easrng** [comment]
129 is the latest stable, it just released yesterday lol https://www.mozilla.org/en-US/firefox/129.0/releasenotes/

**Comment by jakearchibald** [comment]
Hah, maybe they're doing a slow rollout. It still isn't available to me.

**Comment by jakearchibald** [comment]
Ok, I downloaded Firefox Beta and I can reproduce it.

**Comment by jakearchibald** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1912211.

Bloody typical that the very next version of a browser would break this. Hah!

**Comment by jakearchibald** [comment]
The fix should be in Firefox 131.
